# Generated by Django 3.1.4 on 2022-04-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220428_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='has_active_plan',
            field=models.BooleanField(default=False),
        ),
    ]
