# Generated by Django 3.1.4 on 2022-04-29 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220429_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='stripe_product_id',
        ),
    ]
