# Generated by Django 3.1.4 on 2022-04-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_plan_stripe_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='payment_method',
            field=models.CharField(max_length=200),
        ),
    ]
