# Generated by Django 3.1.4 on 2022-05-03 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='wallet_balance',
        ),
    ]
