# Generated by Django 3.1.4 on 2022-05-04 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_customer_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='description',
        ),
    ]
